[package]
name = "conf"
version = "0.1.0"
edition = "2018"
authors = ["wqchen1130@126.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.8"
serde = "1.0"
serde_derive = "1.0"
