#================ 日志相关配置 start ================
#日志输出等级: 1,2,3,4 == Debug,Warning,Info,Error
log_level = 2
#日志文件大小: 单位MB. 超出大小会滚动出新文件. 另外,每天会强制滚动出新文件.
max_log_file_size = 100
#================ 日志相关配置 end ================


#================ 协议导出相关配置 start ================
#源文件目录(*.proto)
src_dir = "proto/ptosrc"
#生成文件目录(*.rs)
out_dir = "proto/src/ptoout"

#协议id编号固定的协议名
init_protos = ["s_login","c_login"]
#================ 协议导出相关配置 end ================

#================ tcp 服务相关配置 start ================
tcp_port = 8081
#================ tcp 服务相关配置 end ================

#================ http 服务相关配置 start ================
http_port = 8082
#================ http 服务相关配置 end ================
